#!/bin/bash

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/debian11"
VAGRANT_BOX_VERSION = "4.2.14"
CPUS_MASTER_NODE    = 4
CPUS_WORKER_NODE    = 2
MEMORY_MASTER_NODE  = 4096
MEMORY_WORKER_NODE  = 4096
WORKER_NODES_COUNT  = 1

Vagrant.configure(2) do |config|
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'
  
  # Kubernetes Master Server
  config.vm.define "kubemaster" do |node|
  
    node.vm.box               = VAGRANT_BOX
    node.vm.box_check_update  = false
    node.vm.box_version       = VAGRANT_BOX_VERSION
    node.vm.hostname          = "kubemaster.local.com"

    node.vm.network "private_network", ip: "172.15.15.100"
  
    node.vm.provider :virtualbox do |v|
      v.name    = "kubemaster"
      v.memory  = MEMORY_MASTER_NODE
      v.cpus    = CPUS_MASTER_NODE
    end
  
    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY_MASTER_NODE
      v.nested  = true
      v.cpus    = CPUS_MASTER_NODE
    end
  
    node.vm.provision "shell", path: "cleanKubeAdmInstall_master.sh"
  
  end

  #Kubernetes Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|

    config.vm.define "kubeworker#{i}" do |node|

      node.vm.box               = VAGRANT_BOX
      node.vm.box_check_update  = false
      node.vm.box_version       = VAGRANT_BOX_VERSION
      node.vm.hostname          = "kubeworker#{i}.local.com"

      node.vm.network "private_network", ip: "172.15.15.10#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "kubeworker#{i}"
        v.memory  = MEMORY_WORKER_NODE
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY_WORKER_NODE
        v.nested  = true
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provision "shell", path: "cleanKubeAdmInstall_worker.sh"

    end

  end
  
end